"""added outfit saving tables

Revision ID: 1f8cfceb3151
Revises: 56d568688f47
Create Date: 2026-01-31 15:43:43.663540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8cfceb3151'
down_revision: Union[str, Sequence[str], None] = '56d568688f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_outfits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('generated_image_url', sa.String(), nullable=False),
    sa.Column('item_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_outfits_id'), 'saved_outfits', ['id'], unique=False)
    op.create_index(op.f('ix_saved_outfits_user_id'), 'saved_outfits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_outfits_user_id'), table_name='saved_outfits')
    op.drop_index(op.f('ix_saved_outfits_id'), table_name='saved_outfits')
    op.drop_table('saved_outfits')
    # ### end Alembic commands ###
