"""Adding purchase note and notification

Revision ID: 2b42ef8cab4b
Revises: d0458db00399
Create Date: 2026-01-05 21:30:38.802262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b42ef8cab4b'
down_revision: Union[str, Sequence[str], None] = 'd0458db00399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seller_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'seller_note')
    # ### end Alembic commands ###
