"""Adding affiliate field to products

Revision ID: 56d568688f47
Revises: 2b42ef8cab4b
Create Date: 2026-01-08 11:49:39.588544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d568688f47'
down_revision: Union[str, Sequence[str], None] = '2b42ef8cab4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('affiliate_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'affiliate_url')
    # ### end Alembic commands ###
