"""Add gender column

Revision ID: afddb65ff6d1
Revises: 379d063d713e
Create Date: 2025-12-09 23:53:54.788245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afddb65ff6d1'
down_revision: Union[str, Sequence[str], None] = '379d063d713e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wardrobe_items', 'gender')
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###
