"""Order and Shipping info

Revision ID: d0458db00399
Revises: da786ac7aeed
Create Date: 2026-01-03 09:53:45.781508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0458db00399'
down_revision: Union[str, Sequence[str], None] = 'da786ac7aeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('carrier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('payout_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payout_info')
    op.drop_column('orders', 'carrier')
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
