"""User purchasing functionality

Revision ID: da786ac7aeed
Revises: ecdeae16dbe2
Create Date: 2025-12-31 20:56:31.716497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da786ac7aeed'
down_revision: Union[str, Sequence[str], None] = 'ecdeae16dbe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
