"""Added User Completed Onboarding Flag

Revision ID: ecdeae16dbe2
Revises: a9c6523f5a89
Create Date: 2025-12-19 08:13:01.568236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdeae16dbe2'
down_revision: Union[str, Sequence[str], None] = 'a9c6523f5a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_onboarding')
    # ### end Alembic commands ###
